### PR TITLE
Feature/docker minecraft support

### PR DESCRIPTION
**Pull request by rainbowdashlabs**
This patch adds support for the https://github.com/itzg/docker-minecraft-server docker image when using bin mounts.

Commands are executed via the integrated rcon-cli. The screen name is used as the container name

### CODE REVIEW

**Comment by nicolaschan** [comment]
Thanks for your PR! A couple questions:

- Does rcon-cli need a password passed in?
- Why do it this way instead of port forward the RCON server port from the docker container to the host? Something like `-p 25575:25575` in the `docker run` command.

**Comment by rainbowdashlabs** [comment]
> Does rcon-cli need a password passed in?

No the rcon-cli is only reachable inside the container and not meant to be exposed. It has no password. The only purpose of the rcon-cli is sending commands into the server runnint inside the container.

> Why do it this way instead of port forward the RCON server port from the docker container to the host? Something like -p 25575:25575 in the docker run command.

Because that would not work with a multi server setup. I have 8 servers running on my host and use a loop to go though all my servers. In order to keep configuration minimal by only entering a screen/container name and the path, all servers need the same configuration and the same rcon-cli access method. Also I want to avoid exposing the rcon-cli to my host network. I trust my firewall, but human errors are still the biggest threat.

Also exposing the port would increase maintainability work on the host since I need to make sure to not reuse ports used by another server. Simply executing the commands via docker exec is the less errorprone way and also the easiest.

**Comment by nicolaschan** [comment]
Thanks! That makes sense. Although I am pretty sure rcon-cli will ask for a password if there is an rcon password configured for your Minecraft server. Here's what I see for mine:

```
minecraft@minecraft-minecraft-58966fcd66-svlrq:~$ rcon-cli
2023/02/08 04:17:35 Failed to connect to RCON serverrcon: authentication failed
```

This PR looks good. I'll merge once we have a test for this case. If I have some free time I'll work a bit on creating one.

**Comment by nicolaschan** [comment]
Sorry it took so long to add that test. Thanks again for making this PR!

**Pull request merged**
